lane :test do
  Fastlane::Actions::SourceEnvFromFileAction.run(
    filepath: '/Users/xiongzenghui/collect_rubygems/fastlane-plugins/fastlane-plugin-source_env_from_file/spec/key_value_file'
  )

  pp ENV['name1']
  pp ENV['name2']
  pp ENV['name3']
  pp ENV['name4']
  pp ENV['name5']
end
